### ISSUE TITLE
Potential overflow

### ISSUE THREAD

**Issue by elichai** [KZen-networks/centipede#9]
Hi, here if `k` is 255 it would overflow by adding 1,
I assume it's not a wanted behavior. 
I think you should change `(k + 1 ) as u32` to `(k as u32 + 1)` or receive `k` as u32 from the first place? 

https://github.com/KZen-networks/centipede/blob/61e615427a596484ee4f01b23d98999b211f5ca0/src/juggling/segmentation.rs#L31

**Comment by omershlo** [comment]
good catch! I changed it according to your first suggestion (+ added some assertion in the calling function). Please let us know if it solves the issue.

**Comment by elichai** [comment]
Had no issue :)
Just noticed it while going through the code.

**Comment by omershlo** [comment]
thank you!
